name: poopgo
description: Septic tank pickup app with Customer and Provider roles.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  uuid: ^4.4.0
  intl: ^0.19.0
  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  # Media and Maps
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  # UI and Design
  google_fonts: ^6.2.1
  # Utils
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  webview_flutter: ^4.4.2
  syncfusion_flutter_pdf: ^31.1.19
  open_filex: ^4.7.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/oferta.txt
    - assets/user_agreement.txt
    - assets/documents/oferta_pooppgo.pdf
    - assets/documents/oferta_pooppgo_updated.docx
    - assets/documents/user_agreement_pooppgo.pdf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "assets/icon/icon.png"
