// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshqHdoGOX5GKpP2lfwYb7-5T37nudp6E',
    appId: '1:31441020994:android:1db7dc64fa701bbeb3e5db',
    messagingSenderId: '31441020994',
    projectId: 'poopgo-a07b9',
    storageBucket: 'poopgo-a07b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvgmueD4V9W78xIg9EoVIBOkZjX24uZw',
    appId: '1:31441020994:ios:5a012f14dbea4319b3e5db',
    messagingSenderId: '31441020994',
    projectId: 'poopgo-a07b9',
    storageBucket: 'poopgo-a07b9.firebasestorage.app',
    iosBundleId: 'com.app.poopgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByvgmueD4V9W78xIg9EoVIBOkZjX24uZw',
    appId: '1:31441020994:ios:5a012f14dbea4319b3e5db',
    messagingSenderId: '31441020994',
    projectId: 'poopgo-a07b9',
    storageBucket: 'poopgo-a07b9.firebasestorage.app',
    iosBundleId: 'com.app.poopgo',
  );
}
