// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrTkesiGSajobJ43vPvuyESPePl8IjHE',
    appId: '1:632068250247:web:your_web_app_id',
    messagingSenderId: '632068250247',
    projectId: 'poogo-2d23d',
    authDomain: 'poogo-2d23d.firebaseapp.com',
    storageBucket: 'poogo-2d23d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcrTkesiGSajobJ43vPvuyESPePl8IjHE',
    appId: '1:632068250247:android:c1d8c57c36be6468f43622',
    messagingSenderId: '632068250247',
    projectId: 'poogo-2d23d',
    storageBucket: 'poogo-2d23d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrTkesiGSajobJ43vPvuyESPePl8IjHE',
    appId: '1:632068250247:ios:your_ios_app_id',
    messagingSenderId: '632068250247',
    projectId: 'poogo-2d23d',
    storageBucket: 'poogo-2d23d.firebasestorage.app',
    iosBundleId: 'com.example.poopgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrTkesiGSajobJ43vPvuyESPePl8IjHE',
    appId: '1:632068250247:ios:your_macos_app_id',
    messagingSenderId: '632068250247',
    projectId: 'poogo-2d23d',
    storageBucket: 'poogo-2d23d.firebasestorage.app',
    iosBundleId: 'com.example.poopgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcrTkesiGSajobJ43vPvuyESPePl8IjHE',
    appId: '1:632068250247:web:your_windows_app_id',
    messagingSenderId: '632068250247',
    projectId: 'poogo-2d23d',
    authDomain: 'poogo-2d23d.firebaseapp.com',
    storageBucket: 'poogo-2d23d.firebasestorage.app',
  );
}

